/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_content_free: (a: number, b: number) => void;
export const __wbg_locales_free: (a: number, b: number) => void;
export const cardFlagBit: (a: number, b: number) => number;
export const cardFlagBitIn: (a: number, b: number, c: number, d: number) => number;
export const cardFlagFieldShape: (a: number, b: number, c: number, d: number) => [number, number];
export const cardFlagFieldValueAny: (a: number, b: number, c: number, d: number) => number;
export const cardFlagFieldValueIn: (a: number, b: number, c: number, d: number, e: number) => number;
export const cardTypeId: (a: number, b: number) => number;
export const content_allBlueprints: (a: number) => [number, number, number, number];
export const content_allTextures: (a: number) => [number, number, number, number];
export const content_aspectInfo: (a: number, b: number, c: number) => [number, number, number, number];
export const content_aspectNames: (a: number) => [number, number];
export const content_aspectValue: (a: number, b: number, c: number, d: number) => [number, bigint];
export const content_cardDef: (a: number, b: number) => [number, number, number, number];
export const content_cardDefId: (a: number, b: number, c: number) => number;
export const content_cardView: (a: number, b: number, c: number) => [number, number, number, number];
export const content_defIdForPacked: (a: number, b: number) => number;
export const content_drawVisuals: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const content_generateTile: (a: number, b: number, c: number, d: number) => number;
export const content_globals: (a: number) => [number, number, number, number];
export const content_matchRecipe: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const content_new: (a: number, b: number) => [number, number, number];
export const content_packedDef: (a: number, b: number, c: number) => number;
export const content_planRecipe: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const content_recipeId: (a: number, b: number, c: number) => number;
export const content_recipeMeta: (a: number, b: number, c: number) => [number, number, number, number];
export const content_recipeName: (a: number, b: number) => [number, number];
export const content_recipeNames: (a: number) => [number, number];
export const content_tilePrims: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const hasCardFlag: (a: number, b: number, c: number, d: number) => number;
export const isHexType: (a: number) => number;
export const locales_new: (a: number, b: number) => [number, number, number];
export const locales_string: (a: number, b: number, c: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
